### ISSUE TITLE
Back button on payment page

### ISSUE THREAD

**Issue by TurkerKucuk** [TurkerKucuk/Pablow_Webapp#20]
1) This button should read "Update" instead of "Back"
2) When user clicks on this button it should redirect the user to Select Page
3) When user reaches "Select Page" this way, the page should not try to get a new quote as it normally does when it is reached from "Search Page". There is already a quote. All the fields in the page should be reinstated from the "Session" property like Session["numberoftravelers"]

**Comment by jaylindsey** [comment]
No 1 is done

**Comment by jaylindsey** [comment]
no 2 is done

**Comment by TurkerKucuk** [comment]
no 3 is done. As I was working on a related issue, I had to touch on this one as well. This is now done.
