### ISSUE TITLE
Policy summary panel in the payment page needs to be realigned

### ISSUE THREAD

**Issue by TurkerKucuk** [TurkerKucuk/Pablow_Webapp#21]
the marked text in the policy summary panel needs to be aligned to the right, instead of aligned center.

![policy_summary_panel](https://cloud.githubusercontent.com/assets/10276667/9690573/c02fc072-5302-11e5-8948-b1b773f1b9ec.PNG)

**Comment by jaylindsey** [comment]
This Is Done
