### ISSUE TITLE
need to add billing zip code in the payment page

### ISSUE THREAD

**Issue by TurkerKucuk** [TurkerKucuk/Pablow_Webapp#22]
When users enter their credit card in the payments page, they also need to enter billing zip code at the same time. Currently payment page does not have a place for this. We need to add it appropriately.

In the screenshot below, you see that there are 3 side by side entries in the page. with the addition of billing zip code, there will be 4 entries total. In this case, put the first 2 entries side by side and then put the remainder of the two entries side by side. 

make the billing zip code entry only to accept 5 digit numeric code as it is earlier done.

![billing_zip_code](https://cloud.githubusercontent.com/assets/10276667/9690627/39a7f3de-5303-11e5-9ae9-247ec6057aac.PNG)

**Comment by jaylindsey** [comment]
This Is Done
