### ISSUE TITLE
need to add name in the confirmation page

### ISSUE THREAD

**Issue by TurkerKucuk** [TurkerKucuk/Pablow_Webapp#23]
We need to add the name and age of the insured person in the confirmation page.
In the first row we should display Policy number and insured amount.
In the second row we should display Name on Policy, Age on Policy and Registered Email

![add_name](https://cloud.githubusercontent.com/assets/10276667/9690758/f5e0c53a-5303-11e5-88b0-245fe525aa77.PNG)

**Comment by jaylindsey** [comment]
This Is Done
