### ISSUE TITLE
alert view in search page needs to be changed

### ISSUE THREAD

**Issue by TurkerKucuk** [TurkerKucuk/Pablow_Webapp#26]
1) Wrap the alert view in a div container 
2) Make the div container's position absolute within the panel
3) Then position the alert label horizontally and vertically center
4) For an example, see the select page example with this id: selectPageOptionPanelInvalidEntryAlertContainer
5) Repeat the same steps for the alert view within the select page update search panel
6) don't forget to remove popoverAlert class (if necessary)

**Comment by TurkerKucuk** [comment]
Do the same thing for the alert view within the select page update search panel

**Comment by jaylindsey** [comment]
this has been added
