### ISSUE TITLE
we need place CSA logo in the select and payment page

### ISSUE THREAD

**Issue by TurkerKucuk** [TurkerKucuk/Pablow_Webapp#43]
see snapshots below:
![capture](https://cloud.githubusercontent.com/assets/10276667/9840741/70eaf840-5a5c-11e5-9c10-62a558195279.PNG)
![capture2](https://cloud.githubusercontent.com/assets/10276667/9840745/869e00c4-5a5c-11e5-96fc-c7721617d941.PNG)

**Comment by jaylindsey** [comment]
CSA logo will run into trouble on minimum width of desktop site.  What about under the fixed update search/ policy summery panels?

**Comment by TurkerKucuk** [comment]
we can always place the logo as position:absolute. Would this still run into trouble?

**Comment by jaylindsey** [comment]
Yeah it will still fall behind the chevrons.

**Comment by jaylindsey** [comment]
We could go smaller with it.  About half the illustrated size?

**Comment by jaylindsey** [comment]
Well two thirds?

**Comment by jaylindsey** [comment]
this is done
