### ISSUE TITLE
name on credit card and credit card number need to share a row

### ISSUE THREAD

**Issue by TurkerKucuk** [TurkerKucuk/Pablow_Webapp#44]
1) name on credit card and credit card number need to share a row instead of name taking an entire row by itself.
2) We need to put an image of accepted credit card types.
3) We need to put a static text right under credit card details:
CSA Travel Protection will charge your credit card, and email an instant policy confirmation.
as seen in this picture:
![capture](https://cloud.githubusercontent.com/assets/10276667/9841441/6275f414-5a65-11e5-9d27-bfb56240ca59.PNG)

**Comment by jaylindsey** [comment]
CSA notice added to bottom of CC info form.

**Comment by jaylindsey** [comment]
Closing
