### ISSUE TITLE
remove the i agree check button

### ISSUE THREAD

**Issue by TurkerKucuk** [TurkerKucuk/Pablow_Webapp#45]
in the payment page, customer no longer wants the agree check button. instead he wants the following verbage somewhere appropriate:

By clicking on the "Pay" button, you agree to the Terms of Service (and link then to the Terms of Service)

**Comment by TurkerKucuk** [comment]
This is the terms of Service:

1.1	Terms of Service
Pablow, Inc. reserves the right to amend the information on this website at any time and without prior notice. The Terms and Conditions may be amended at any time and Pablow, Inc. will provide notice of such amendments by posting the changes on the website.
Correspondence
By using this site you acknowledge that our principal means of communication is via email and therefore it is important that you to ensure that we have your current email address. All notices sent, will be deemed delivered at the time of sending it. It is every customer's responsibility to inform Pablow, Inc. if there is any change to this address.
Changes to premiums
We reserve the right to change the premium charged for a policy at any time without notice. This does not affect customers who have already purchased a policy.
Refunds
Within 10 days of purchase: If you decide that a policy does not meet your needs, your premium will be refunded in full. If however, within the 10 days and/or since inception you have travelled, made a claim or intend to make a claim, or if the policy has started, then the premium will not be refunded.
Payments
Payment is by credit or debit card and is required at the time you purchase the policy. Pablow, Inc. may, at its sole discretion, cease to provide service or payment to certain users or to users paying with certain credit cards. Pablow, Inc. reserves the right without explanation to refuse purchase from any customer.
Disclaimer and Limitation of Liability
Pablow, Inc. will not have any liability for any loss or damage without limitation that are alleged to have resulted from the Pablow, Inc. website or its content, including but not limited to, delays or interruptions in service or communication, a customer's or any other person's misuse of the site and its content, and any errors or omissions in content. We accept no liability out of the use neither of this web site nor of any links that are provided to any third party site. None of the information provided on this website is intended to be used as financial advice or any other advice.
Pablow, Inc. may at any time require the customer to provide documentation to confirm their identity at any time and at Pablow, Inc.'s sole discretion. The use of proxy servers, except for those assigned by ISPs for normal use is strictly forbidden. This rule also applies to, but is not limited to, anonymous website proxies and any other means to hide your identity.
Third Party Services
Pablow, Inc. accepts no responsibility for any goods or services referred to on its website not under its control. Pablow, Inc. makes no warranties or representations for these services. The customer indemnifies Pablow, Inc. for any loss or damage arising from the use of these goods or services from any third party.

**Comment by jaylindsey** [comment]
This Is done
