### ISSUE TITLE
payment page share buttons

### ISSUE THREAD

**Issue by TurkerKucuk** [TurkerKucuk/Pablow_Webapp#46]
these need to be developed

**Comment by TurkerKucuk** [comment]
share button for facebook, twitter and google plus have been implemented. we need a send an email button. this is still under development.

**Comment by TurkerKucuk** [comment]
we need to find a javascript function from the internet that essentially opens up the default mail client.

**Comment by jaylindsey** [comment]
Email button is fixed with mailto link
Closing ticket
