### ISSUE TITLE
when pay button is pressed button needs to be disabled

### ISSUE THREAD

**Issue by TurkerKucuk** [TurkerKucuk/Pablow_Webapp#48]
this needs to done on the client side - i.e. javascript. search for this issue and apparently there are a number of solutions on the web.

**Comment by jaylindsey** [comment]
Spent some time looking for this...where is the onclick function?

**Comment by jaylindsey** [comment]
This Is done

**Comment by TurkerKucuk** [comment]
initial solution was not working. The actual solution was to hide the original button, not disable it. Disabled asp buttons don't really get disabled because they run on the server; therefore, they need to be disabled on the server side. However, simply hiding it and swapping it with another button is the way to go.
