### ISSUE TITLE
1 Search page: items to be changed - markedup 1-5 (see screen shot and text)

### ISSUE THREAD

**Issue by stevepablow** [TurkerKucuk/Pablow_Webapp#54]
Items highlighted 1-3

1. In search box - change text to Vacation Rental Insurance & remove the "number of travellers" field.
2. In header Remove text and just use the white icon (i loaded) and link as "home"
3. Footer links: Use just this text in the footer and link to relevant pages as per extra pages doc - but position them in a way that looks good on your screen and maybe FB & Twitter icons.
4. 
![image](https://cloud.githubusercontent.com/assets/9828657/9977602/8849dbb6-5ed3-11e5-9f56-f18f8070a2df.png)

5. 
![image](https://cloud.githubusercontent.com/assets/9828657/9977625/1272cd5c-5ed4-11e5-96aa-86b49cb7eb65.png)

![search-page-5-markedup-2](https://cloud.githubusercontent.com/assets/9828657/9977618/eea198a4-5ed3-11e5-85d2-30367387f0fc.jpg)

**Comment by stevepablow** [comment]
white logo - to go into the header
![pablow_icon_white](https://cloud.githubusercontent.com/assets/9828657/9923991/b30d4cb2-5cc0-11e5-9b8b-4dfda30bdf97.png)

**Comment by TurkerKucuk** [comment]
item 1 - done: 
![item16](https://cloud.githubusercontent.com/assets/10276667/10006361/77a45f10-6082-11e5-89e8-2c2d857b1e0b.PNG)

We need decision on the number of travelers section.

**Comment by TurkerKucuk** [comment]
item 2 done:
![item17](https://cloud.githubusercontent.com/assets/10276667/10006380/9be0b900-6082-11e5-882d-31fb4e420c12.PNG)

**Comment by TurkerKucuk** [comment]
how do you like this arrangement?
![item18](https://cloud.githubusercontent.com/assets/10276667/10010499/e67e6d84-60b1-11e5-83a7-8aa5806e477f.PNG)

**Comment by TurkerKucuk** [comment]
I also need "Powered by Pablow" image

**Comment by stevepablow** [comment]
yeah that looks fine! i guess in later versions we can integrate menu into
the top menu as part of the responsive them

ok I'll add a powered by logo to new issue

On Mon, Sep 21, 2015 at 10:41 PM, Turker <notifications@github.com> wrote:

> how do you like this arrangement?
> [image: item18]
> <https://cloud.githubusercontent.com/assets/10276667/10010499/e67e6d84-60b1-11e5-83a7-8aa5806e477f.PNG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TurkerKucuk/Pablow_Webapp/issues/54#issuecomment-142170965>
> .
>



-- 

________________

Steve Sherlock
CEO

 Pablow Inc
*Targeted Travel Insurance*

321 E. Walnut, Suite 130
Des Moines, IA 50309
www.Pablow.com <http://www.pablow.com/>
steve@pablow.com
+1 650 471 4495
Skype: SteveSherlock2

**Comment by TurkerKucuk** [comment]
item 4 and 5 done:
![item20](https://cloud.githubusercontent.com/assets/10276667/10172557/97fb46c4-66a5-11e5-89d2-7c6a3f7bf71d.PNG)
