### ISSUE TITLE
2 Quote page Full edits text and screen shot

### ISSUE THREAD

**Issue by stevepablow** [TurkerKucuk/Pablow_Webapp#56]
1. add text: "Policy Quote"
2. Change text to: "Insurance Coverage" (& add: Underwritten by Generali U.S. Branch)
3. Change to: "Maximum Benefit Per Person *" (at bottom of table add: "* Maximum 10 People Per Plan") & make all benefit amounts Per Person i.e. baggage $1,000 instead of $10,000
4. Change text to: "10-day Free Look" & (on right side change to: "You can cancel your plan within 10 days, provided you haven’t filed a claim or departed on your trip.")
5. Change text to: "Expand Details" & "Hide Details" & add a down and up arrow to indicate it opens and closes.
6. Remove the "Number of Travellers" field.
7. Change text to: "Insurance Coverage" (& add: Underwritten by Generali U.S. Branch)
8. Change text to: "Maximum Benefit Per Person *"
9. Change amounts to Per Person and add cents .00
10. Add text: "$200 Per Day, Per Person"
11. Add text: "and Transportation" 
12. I suggest removing this whole section - and if clients want more detail they can click on Policy Summary or Full Policy Details - at bottom of screen
13. Change text to: Vacation Rental Insurance Coverage
14. Move and Change text: Full Policy Details or Policy Summary (add text: (opens in new window)
15. Add to coverage items: Medical & Dental (with $25,000.00
![quote-page-4-top-and-bottom-marked-up3](https://cloud.githubusercontent.com/assets/9828657/9978244/1e98e76c-5eeb-11e5-8b11-45793e28cedd.jpg)
 value)

**Comment by TurkerKucuk** [comment]
item 1 - done
![item1](https://cloud.githubusercontent.com/assets/10276667/9997932/7304dd46-6054-11e5-897f-d841c844dc07.PNG)

**Comment by TurkerKucuk** [comment]
item 2 - done
![item2](https://cloud.githubusercontent.com/assets/10276667/9997950/8be29524-6054-11e5-88a7-35815a500de4.PNG)

**Comment by TurkerKucuk** [comment]
item 3 & 4 - done
![item3_4](https://cloud.githubusercontent.com/assets/10276667/9997971/abb22806-6054-11e5-932c-871a62eb771d.PNG)

**Comment by TurkerKucuk** [comment]
item 5 - done
![item5 1](https://cloud.githubusercontent.com/assets/10276667/9998506/072960f8-6057-11e5-8643-f65c7683fae9.PNG)
![item5 2](https://cloud.githubusercontent.com/assets/10276667/9998507/08b0b7c8-6057-11e5-934b-faefec762d7b.PNG)

**Comment by TurkerKucuk** [comment]
item 7 - done
![item7](https://cloud.githubusercontent.com/assets/10276667/9998772/726defb8-6058-11e5-8abf-8bb31e5d9764.PNG)

**Comment by TurkerKucuk** [comment]
item 8 thru 15 done
![item8_15](https://cloud.githubusercontent.com/assets/10276667/10000220/67e2ef6e-6060-11e5-8134-0850062d32a9.PNG)

**Comment by TurkerKucuk** [comment]
skipping item 6 for now as we have not decided on a way forward.

**Comment by stevepablow** [comment]
what if you defaulted travellers to 1 and hid the fields?

but yeah let's sort all other things first and we can consider this then.

**Comment by TurkerKucuk** [comment]
We can hide the fields where hiding won't be disruptive to the page 
layout or logic - which I already did in payment page. As for the other 
pages, unfortunately, it is more involved than that so I can't do it in 
an afternoon. We have to implement that separately or perhaps as a part 
of phase #2. Alternatively, we can create a SOW and implement it right 
away. I am happy to talk it over and explain the details and why it is 
more involved for home and select pages but not with the payment page.

Turker

**Comment by stevepablow** [comment]
as per previous ticket - happy for splash and #travellers to be SOW

yeah - if figured there could be complications given the logic was built in
(and we will probably be able to use #travellers logic on other products as
i am talking to AIG who have a product that requires passengers and age)

On Mon, Sep 21, 2015 at 9:32 PM, Turker <notifications@github.com> wrote:

> We can hide the fields where hiding won't be disruptive to the page
> layout or logic - which I already did in payment page. As for the other
> pages, unfortunately, it is more involved than that so I can't do it in
> an afternoon. We have to implement that separately or perhaps as a part
> of phase #2. Alternatively, we can create a SOW and implement it right
> away. I am happy to talk it over and explain the details and why it is
> more involved for home and select pages but not with the payment page.
>
> Turker
>
> On 9/21/2015 1:42 PM, stevepablow wrote:
> >
> > what if you defaulted travellers to 1 and hid the fields?
> >
> > but yeah let's sort all other things first and we can consider this then.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/TurkerKucuk/Pablow_Webapp/issues/56#issuecomment-142071902
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TurkerKucuk/Pablow_Webapp/issues/56#issuecomment-142162269>
> .
>



-- 

________________

Steve Sherlock
CEO

 Pablow Inc
*Targeted Travel Insurance*

321 E. Walnut, Suite 130
Des Moines, IA 50309
www.Pablow.com <http://www.pablow.com/>
steve@pablow.com
+1 650 471 4495
Skype: SteveSherlock2
