### ISSUE TITLE
3 Payment Page edits text and screen shot

### ISSUE THREAD

**Issue by stevepablow** [TurkerKucuk/Pablow_Webapp#57]
1. Change text from Policy to: Plan (in two highlighted spots)
2. Use the Per Person value of $1,000.00
3. Remove the "Number of Travellers" field and text
4. Remove the age fields for extra travellers and adjust the spacing.
5. Slight change to text: CSA Travel Protection will charge your credit card, and email a policy confirmation.
6. Add: SSL certificate logo
![payment-page-mocked-up-1](https://cloud.githubusercontent.com/assets/9828657/9978112/bf681b36-5ee6-11e5-8f2d-17d6d1122d09.jpg)

**Comment by TurkerKucuk** [comment]
item 1,2 and 3 - done:
![item9](https://cloud.githubusercontent.com/assets/10276667/10004979/2d662e9a-607a-11e5-87a5-3fe315637bdc.PNG)

**Comment by TurkerKucuk** [comment]
item 4 done - 
![item10](https://cloud.githubusercontent.com/assets/10276667/10005010/4fc2162a-607a-11e5-9be0-2e6d285eaf1d.PNG)

**Comment by TurkerKucuk** [comment]
item 5 - done
![item11](https://cloud.githubusercontent.com/assets/10276667/10005025/6f357574-607a-11e5-9916-3a24c734ef24.PNG)

**Comment by TurkerKucuk** [comment]
bonus item: now plan summary panel to the left is sticky - meaning that as you scroll down, you can still see the policy cost and other travel details.
![item12](https://cloud.githubusercontent.com/assets/10276667/10005049/a7d068e4-607a-11e5-898b-e911319a0998.PNG)
![item13](https://cloud.githubusercontent.com/assets/10276667/10005063/c75ff40e-607a-11e5-9334-d460fda952d5.PNG)

**Comment by TurkerKucuk** [comment]
bonus item: hover over the pay button to see how much the credit card will be charged.
![item14](https://cloud.githubusercontent.com/assets/10276667/10005194/8160d6fc-607b-11e5-8aa2-97b603bc4533.png)

**Comment by TurkerKucuk** [comment]
this ticket has been closed except for item 6. For that item, another ticket has been opened. please follow the status of that item in issue #64;
