### ISSUE TITLE
4 Confirmation Page text edits and screen shot

### ISSUE THREAD

**Issue by stevepablow** [TurkerKucuk/Pablow_Webapp#58]
1. slight text change, replace "Policy Confirmation" with: "plan"
2. Remove the insurance summary section (advised by CSA)
3. Remove "number of travelers" field
![confirmation-page-marked-up-2](https://cloud.githubusercontent.com/assets/9828657/9978196/24d8191a-5ee9-11e5-9e4c-9ea9fe6bb428.jpg)

**Comment by TurkerKucuk** [comment]
item 1-3 done.
![item14](https://cloud.githubusercontent.com/assets/10276667/10005807/fc4a1272-607e-11e5-91a6-3e6baca7babc.png)
