### ISSUE TITLE
New Splash Image for Search Page

### ISSUE THREAD

**Issue by stevepablow** [TurkerKucuk/Pablow_Webapp#59]
Turker - can you please use this image for the search splash image. Its high definition.

thanks,
![shutterstock_274630382](https://cloud.githubusercontent.com/assets/9828657/9983163/bde6ac50-5fb8-11e5-9fc2-2b336babf472.jpg)

Steve

**Comment by stevepablow** [comment]
also - just something to consider at this stage i.e. making the search box party transparent. Airbnb for example make a lot of images on their site transparent so the splash image looks better.

see example attached
![vr-deck-splash-transparent](https://cloud.githubusercontent.com/assets/9828657/9983198/089989e2-5fba-11e5-8c6a-5e0c2817b61a.jpg)

**Comment by stevepablow** [comment]
or like this if we really want to be "the cool kids" ;-) 

![vr-deck-splash-transparent-3](https://cloud.githubusercontent.com/assets/9828657/9983328/92d75956-5fbd-11e5-8b2d-fa56982282de.jpg)

See how homeaway.com does it

**Comment by stevepablow** [comment]
Turker - happy for you to consider a change request fee to be able to get the search page to look like this :+1:

**Comment by stevepablow** [comment]
1. can you right justify the text to align up with the CSA logo and make the number of words per line about the same.
2. can you try add a transparent blue behind the text so that it 

see mockup
![search-edit-text-placement](https://cloud.githubusercontent.com/assets/9828657/10124904/287e32a8-6528-11e5-9d09-ba52570c69ff.jpg)

**Comment by TurkerKucuk** [comment]
Steve, 

please take a look at the new home page layout. What do you think?
![item21](https://cloud.githubusercontent.com/assets/10276667/10176421/33f49b34-66ba-11e5-8698-39268688a88f.PNG)

**Comment by stevepablow** [comment]
good stuff! looks great!

only thing - the blue get quote button blends in a bit with the blue sky. I
suggest making button orange - same colour that we use on quote page?

On Tue, Sep 29, 2015 at 2:57 PM, Turker <notifications@github.com> wrote:

> Steve,
>
> please take a look at the new home page layout. What do you think?
> [image: item21]
> <https://cloud.githubusercontent.com/assets/10276667/10176421/33f49b34-66ba-11e5-8698-39268688a88f.PNG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TurkerKucuk/Pablow_Webapp/issues/59#issuecomment-144171139>
> .
>



-- 

________________

Steve Sherlock
CEO

 Pablow Inc
*Targeted Travel Insurance*

321 E. Walnut, Suite 130
Des Moines, IA 50309
www.Pablow.com <http://www.pablow.com/>
steve@pablow.com
+1 650 471 4495
Skype: SteveSherlock2

**Comment by TurkerKucuk** [comment]
Ok will do.

**Comment by TurkerKucuk** [comment]
this ticket is implemented.
