### ISSUE TITLE
select page layout needs to fixed

### ISSUE THREAD

**Issue by TurkerKucuk** [TurkerKucuk/Pablow_Webapp#6]
1) main panel needs to be extended a little bit so that full benefits panel is contained
2) create go to top button right underneath the main panel when it is extended. it should be invisible when panel is closed.
3) *not critical* - ideally full benefits panel should slide from left or right into the main panel instead of slidedown effect.
4) links in legal notice section should automatically open in a different page/tab

**Comment by jaylindsey** [comment]
Fixed issue 1

**Comment by TurkerKucuk** [comment]
5) use one of the jquery ui icons for "go to top" button for additional visual feedback
6) "go to top" button should be visible within the main-panel (gray area).
7) change the styling of the select page so that it matches the styling of the payment page where panels scale nicely between 1024px and 768px.

**Comment by jaylindsey** [comment]
Fixed section 2 except visibility issues.

**Comment by jaylindsey** [comment]
Fixed Section 4

**Comment by jaylindsey** [comment]
Fixed Section 5

**Comment by jaylindsey** [comment]
Fixed Section 6

**Comment by jaylindsey** [comment]
Style sheets now broken up.

**Comment by jaylindsey** [comment]
All issues addressed closing
