### ISSUE TITLE
What is Description of Coverages

### ISSUE THREAD

**Issue by TurkerKucuk** [TurkerKucuk/Pablow_Webapp#61]
In the extras documentation, you refer to Description of Coverages. This reference is used within the FAQ section under what is a covered event, you want to live link somewhere. Can you explain what is this Description of Coverages page?

![item19](https://cloud.githubusercontent.com/assets/10276667/10031069/ab267530-6140-11e5-8983-010b338b5d64.PNG)

**Comment by TurkerKucuk** [comment]
Is the description of coverage another page in CSA's website. I found this there:

https://www.vacationrentalinsurance.com/certpolicyold.do?pclass=w

**Comment by stevepablow** [comment]
not sure what I was thinking with that - maybe I was thinking the "product
page" but instead I suggest linking it to the Policy Summary PDF link (same
one you are using on quote page
http://whitelabel-pablow-lodgix.azurewebsites.net/Assets/G-330CSA%20Why%20Buy%20Flyer%20-%20Overview.pdf
)

thanks

On Tue, Sep 22, 2015 at 3:43 PM, Turker <notifications@github.com> wrote:

> Assigned #61 <https://github.com/TurkerKucuk/Pablow_Webapp/issues/61> to
> @stevepablow <https://github.com/stevepablow>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TurkerKucuk/Pablow_Webapp/issues/61#event-416321991>.
>



-- 

________________

Steve Sherlock
CEO

 Pablow Inc
*Targeted Travel Insurance*

321 E. Walnut, Suite 130
Des Moines, IA 50309
www.Pablow.com <http://www.pablow.com/>
steve@pablow.com
+1 650 471 4495
Skype: SteveSherlock2

**Comment by stevepablow** [comment]
that link doesn't seem to work so well - so on that other link "Description
of Coverage" I suggest we link that too the same summary PDF

On Tue, Sep 22, 2015 at 3:58 PM, Turker <notifications@github.com> wrote:

> Is the description of coverage another page in CSA's website. I found this
> there:
>
> https://www.vacationrentalinsurance.com/certpolicyold.do?pclass=w
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TurkerKucuk/Pablow_Webapp/issues/61#issuecomment-142419865>
> .
>



-- 

________________

Steve Sherlock
CEO

 Pablow Inc
*Targeted Travel Insurance*

321 E. Walnut, Suite 130
Des Moines, IA 50309
www.Pablow.com <http://www.pablow.com/>
steve@pablow.com
+1 650 471 4495
Skype: SteveSherlock2
