### ISSUE TITLE
Footer disclaimer incorrect

### ISSUE THREAD

**Issue by stevepablow** [TurkerKucuk/Pablow_Webapp#67]
For the footer use the text found at this page (it comprises a head & body)

1. http://www.csainsuranceservices.com/disclaimers/
2. Under the disclaimer text add: Copyright© 2015 Pablow, Inc. Company Number: 5720334

**Comment by TurkerKucuk** [comment]
done. please check the website and let us know if it meets the standards.

**Comment by stevepablow** [comment]
cool  - thanks. look good - I've sent to CSA to start their review

On Tue, Sep 29, 2015 at 12:21 PM, Turker <notifications@github.com> wrote:

> done. please check the website and let us know if it meets the standards.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TurkerKucuk/Pablow_Webapp/issues/67#issuecomment-144126572>
> .
>



-- 

________________

Steve Sherlock
CEO

 Pablow Inc
*Targeted Travel Insurance*

321 E. Walnut, Suite 130
Des Moines, IA 50309
www.Pablow.com <http://www.pablow.com/>
steve@pablow.com
+1 650 471 4495
Skype: SteveSherlock2
