### ISSUE TITLE
Payment button 

### ISSUE THREAD

**Issue by stevepablow** [TurkerKucuk/Pablow_Webapp#70]
Lets talk about this tomorrow

1. even when I have fill in all the fields the hover message says I need to fill in all fields.

2. when i click the pay button - it moves the page back up to top - which i find a bit confusing as I have to scroll down to see the next hover message saying how much I will be charged.

3. As customer arrives on this page - maybe we could default the pay button active with the hover message "You're credit card will be charged $150.00" & only if all fields have not been completed then do the validation upon clicking pay button

**Comment by TurkerKucuk** [comment]
yes, i think this is an issue with the Safari browser. It doesn't work like this on Firefox or Chrome.

**Comment by TurkerKucuk** [comment]
this issue has been resolved.
