### ISSUE TITLE
contact us page

### ISSUE THREAD

**Issue by TurkerKucuk** [TurkerKucuk/Pablow_Webapp#72]
Using the attached storyboard as a guide, please create a contact us page form.
[Pablow_Webapp_Addendum_Storyboard.pdf](https://github.com/TurkerKucuk/Pablow_Webapp/files/4697/Pablow_Webapp_Addendum_Storyboard.pdf)

**Comment by TurkerKucuk** [comment]
We need to use the jotforms. www.jotform.com.

**Comment by jaylindsey** [comment]
this is done
