### ISSUE TITLE
Confirmation Page - align to centre

### ISSUE THREAD

**Issue by stevepablow** [TurkerKucuk/Pablow_Webapp#77]
On confirmation page can you align to middle (its currently on the left) - see screenshot using chrome

tx
![confirmation-page](https://cloud.githubusercontent.com/assets/9828657/10201448/c319d89e-6771-11e5-9d21-68bc6870b191.jpg)

**Comment by TurkerKucuk** [comment]
done and published.

**Comment by stevepablow** [comment]
just saw the SSL - woohoo well done!



On Wed, Sep 30, 2015 at 2:15 PM, Turker <notifications@github.com> wrote:

> Closed #77 <https://github.com/TurkerKucuk/Pablow_Webapp/issues/77>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TurkerKucuk/Pablow_Webapp/issues/77#event-423464188>.
>



-- 

________________

Steve Sherlock
CEO

 Pablow Inc
*Targeted Travel Insurance*

321 E. Walnut, Suite 130
Des Moines, IA 50309
www.Pablow.com <http://www.pablow.com/>
steve@pablow.com
+1 650 471 4495
Skype: SteveSherlock2
