### ISSUE TITLE
CSA FINAL Compliance Changes 1

### ISSUE THREAD

**Issue by stevepablow** [TurkerKucuk/Pablow_Webapp#79]
Hi Turker

CSA have fully reviewed the site and made following requests. I will add each one here for easy tracking. 

If you have any questions any of them let me know. I'll email you their orginal review document aswell in case it will help with any items.

1st item: remove csa logo and move the Generali logo up into that place.
![csa-complaince-change-1](https://cloud.githubusercontent.com/assets/9828657/10408455/8ca34ec2-6ec3-11e5-8b35-386e41493636.jpg)

**Comment by TurkerKucuk** [comment]
CSA logo removed, Generali logo was put in its place.

![item22](https://cloud.githubusercontent.com/assets/10276667/10432498/ff8c652c-70d0-11e5-947b-1280059f38d8.PNG)
