### ISSUE TITLE
Items 2 & 3 - text changes

### ISSUE THREAD

**Issue by stevepablow** [TurkerKucuk/Pablow_Webapp#80]
item 2: Missing "...of purchased"
It should say:
You can cancel your plan within 10 days of purchase as long as you not filed a claim or departed on your trip.

item 3: Change to:
*plan limits also apply
![csa-complaince-change-2-3](https://cloud.githubusercontent.com/assets/9828657/10408514/d5b8e62a-6ec4-11e5-81b4-23e8edb11a38.jpg)

**Comment by TurkerKucuk** [comment]
done.

![item23](https://cloud.githubusercontent.com/assets/10276667/10432643/1755c076-70d2-11e5-87f1-03aaa443a185.PNG)
