### ISSUE TITLE
item 4 - moving full coverage items up (hold this one)

### ISSUE THREAD

**Issue by stevepablow** [TurkerKucuk/Pablow_Webapp#81]
They want us to move all coverage items together :-1: 

I will confirm with them what exactly they want, but I was thinking maybe if we did it like this, they might accept it. 

Item 4: at top we add text: Summary of Coverage

Item 4: and move the bottom section up and make same width - with text saying: Expanded List of Vacation Rental Insurance Coverage

Let me know your thoughts.

![csa-complaince-change-4 1](https://cloud.githubusercontent.com/assets/9828657/10408662/a4cf7ae2-6ec9-11e5-9acd-5b858de20c90.jpg)

**Comment by TurkerKucuk** [comment]
Why do we have to show all of the benefits at once? Can't we say - benefit highlights and show only the ones we want to advertise? And put a button/link saying here is the full benefits?

**Comment by stevepablow** [comment]
that's what I thought/hoped!

It seems that whenever any coverage list is displayed - the whole list
needs to be displayed.

for example for item 6 & 7 #83 - they wrote "All coverages need to be
listed here (or just remove coverages and leave dates and trip cost)."

I will email them that sample screen shot (with summary & full list) and
see if they will accept something like that. Or would you suggest
displaying it some other way?



On Mon, Oct 12, 2015 at 12:32 PM, Turker <notifications@github.com> wrote:

> Why do we have to show all of the benefits at once? Can't we say - benefit
> highlights and show only the ones we want to advertise? And put a
> button/link saying here is the full benefits?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TurkerKucuk/Pablow_Webapp/issues/81#issuecomment-147469462>
> .
>



-- 

________________

Steve Sherlock
CEO

 Pablow Inc
*Targeted Travel Insurance*

321 E. Walnut, Suite 130
Des Moines, IA 50309
www.Pablow.com <http://www.pablow.com/>
steve@pablow.com
+1 650 471 4495
Skype: SteveSherlock2

**Comment by TurkerKucuk** [comment]
I am curious as to why clearly stating that this is just a highlight of benefits is not sufficient. We are also and clearly providing the link for the full list just below the screen (see screenshot). This kind of technique is used everywhere.

![item26](https://cloud.githubusercontent.com/assets/10276667/10434969/a5fe0b02-70e2-11e5-8990-80ac2991386e.PNG)


![item26](https://cloud.githubusercontent.com/assets/10276667/10434809/590b1e9e-70e1-11e5-86ec-ffcefdca6fba.PNG)

**Comment by stevepablow** [comment]
I sent them the screenshot showing the highlights/summary and full list
both displayed as default open - to see what they will allow.

I am pretty sure this is related to insurance regulations - where the
regulation probably says something like "the full list of benefits must be
displayed" (where the customer later can't complain and say "but I didn't
see the full list etc"

I know it's very bureaucratic (welcome to insurance ;-) - unfortunately
we've had to fit in with this over 4 years with Allianz in Australia where
they pretty much control every word we use on the pages.





On Mon, Oct 12, 2015 at 1:10 PM, Turker <notifications@github.com> wrote:

> I am curious as to why clearly stating that this is just a highlight of
> benefits is not sufficient. We are also and clearly providing the link for
> the full list just below the screen (see screenshot). This kind of
> technique is used everywhere.
>
> [image: item26]
> <https://cloud.githubusercontent.com/assets/10276667/10434969/a5fe0b02-70e2-11e5-8990-80ac2991386e.PNG>
>
> [image: item26]
> <https://cloud.githubusercontent.com/assets/10276667/10434809/590b1e9e-70e1-11e5-86ec-ffcefdca6fba.PNG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TurkerKucuk/Pablow_Webapp/issues/81#issuecomment-147479046>
> .
>



-- 

________________

Steve Sherlock
CEO

 Pablow Inc
*Targeted Travel Insurance*

321 E. Walnut, Suite 130
Des Moines, IA 50309
www.Pablow.com <http://www.pablow.com/>
steve@pablow.com
+1 650 471 4495
Skype: SteveSherlock2

**Comment by stevepablow** [comment]
Turker - CSA came back and said its ok to display it as the above screenshot - i.e. with summary and text on top and expanded version below. Main thing I think from their point of view, was to show all on one page.

I suggest keeping the same functionality i.e. to allow it to expand/collapse - and make it defaulted as expanded underneath the summary as above (and if customer wants to collapse it they can)

**Comment by TurkerKucuk** [comment]
Hi Steve,

Do you want to display the summary like this?

![item27](https://cloud.githubusercontent.com/assets/10276667/10491698/7f5f44ca-726d-11e5-9faf-a32bf03a0464.PNG)

**Comment by TurkerKucuk** [comment]
or like this:
![item28](https://cloud.githubusercontent.com/assets/10276667/10491757/da85673a-726d-11e5-895d-c3060d979554.PNG)

**Comment by stevepablow** [comment]
Yeah the 2nd one - so that the csa compliance text is displayed otherwise
they'll need to review again

On Wednesday, October 14, 2015, Turker <notifications@github.com> wrote:

> or like this:
> [image: item28]
> <https://cloud.githubusercontent.com/assets/10276667/10491757/da85673a-726d-11e5-895d-c3060d979554.PNG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TurkerKucuk/Pablow_Webapp/issues/81#issuecomment-148123853>
> .
>


-- 

________________

Steve Sherlock
CEO

 Pablow Inc
*Targeted Travel Insurance*

321 E. Walnut, Suite 130
Des Moines, IA 50309
www.Pablow.com <http://www.pablow.com/>
steve@pablow.com
+1 650 471 4495
Skype: SteveSherlock2

**Comment by TurkerKucuk** [comment]
Can you tell me what exactly we should write on the expanded section?
![item29](https://cloud.githubusercontent.com/assets/10276667/10492110/a60496da-7299-11e5-8b91-9f341232deb5.PNG)

**Comment by TurkerKucuk** [comment]
Please let me know if this looks good. Page now automatically expands and displays all the content after load.
![item30](https://cloud.githubusercontent.com/assets/10276667/10492474/f5f972aa-7271-11e5-9f94-48abc0675984.PNG)

**Comment by stevepablow** [comment]
I think this will do for now:

Expanded: Vacation Rental Insurance Coverage

We can change later if we think other language converts better and get
reviewed when we submit sites to csa

On Wednesday, October 14, 2015, Turker <notifications@github.com> wrote:

> Can you tell me what exactly we should write on the expanded section?
> [image: item29]
> <https://cloud.githubusercontent.com/assets/10276667/10492110/a60496da-7299-11e5-8b91-9f341232deb5.PNG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TurkerKucuk/Pablow_Webapp/issues/81#issuecomment-148127726>
> .
>


-- 

________________

Steve Sherlock
CEO

 Pablow Inc
*Targeted Travel Insurance*

321 E. Walnut, Suite 130
Des Moines, IA 50309
www.Pablow.com <http://www.pablow.com/>
steve@pablow.com
+1 650 471 4495
Skype: SteveSherlock2

**Comment by TurkerKucuk** [comment]
Alright. Changes are implemented. Website is published.
