### ISSUE TITLE
item 5 - change link url

### ISSUE THREAD

**Issue by stevepablow** [TurkerKucuk/Pablow_Webapp#82]
items 5

for the "Full Policy Details" change the link destination to http://www.csatravelprotection.com/certpolicy.do?product=G-330CSA

Summary sheet seems to be ok.
![csa-complaince-change-5](https://cloud.githubusercontent.com/assets/9828657/10408686/5bbe14ac-6eca-11e5-9874-195eb16cacd8.jpg)

**Comment by TurkerKucuk** [comment]
link changed as requested.
