### ISSUE TITLE
item 6 & 7

### ISSUE THREAD

**Issue by stevepablow** [TurkerKucuk/Pablow_Webapp#83]
Item 6: Change text to: Guest Protect Plan (not protection)

Item 7: remove this section because they reckon if we are going to show the coverage items we have to show them all or not at all.

we can keep dates and trip cost.
![csa-complaince-change-6-7](https://cloud.githubusercontent.com/assets/9828657/10408722/694bc870-6ecb-11e5-8dfb-9cf1c6a76754.jpg)

**Comment by TurkerKucuk** [comment]
Now states "Guest Protect Plan"
trip cancellation, trip interruption and baggage references are removed.

![item24](https://cloud.githubusercontent.com/assets/10276667/10432994/615f3dee-70d4-11e5-84e0-cea4fe34ded2.PNG)
