### ISSUE TITLE
items 8 and 9 

### ISSUE THREAD

**Issue by stevepablow** [TurkerKucuk/Pablow_Webapp#84]
item 8 - replace text under red line with: purchase.

item 9 - change link to: www.csatravelprotection.com/certpolicy.do?product=G-330CSA
![csa-complaince-change-8-9](https://cloud.githubusercontent.com/assets/9828657/10408758/e8418588-6ecc-11e5-900a-1354daa5385c.jpg)

**Comment by TurkerKucuk** [comment]
implemented as requested.
