### ISSUE TITLE
items 10,11 and 12

### ISSUE THREAD

**Issue by stevepablow** [TurkerKucuk/Pablow_Webapp#85]
item 10: change entire text to this:

An insurance policy is not designed to cover every possible event that might happen to you. Events that this plan provides coverage for can be found in the Description of Coverage or Policy.

Item 11: Change the link to: www.csatravelprotection.com/certpolicy.do/product=G-330CSA

item 12: Change entire text to: 
Vacation rental plans are usually offered at the time of reservation; this plan is available for purchase up until the final payment is due. Please contact your Vacation Rental Management Company with any procedural questions related to purchasing.
![csa-complaince-change-10-11-12](https://cloud.githubusercontent.com/assets/9828657/10408791/17774f08-6ece-11e5-9013-d7a9aad854bf.jpg)

**Comment by TurkerKucuk** [comment]
![item25](https://cloud.githubusercontent.com/assets/10276667/10433213/ab382902-70d5-11e5-86bf-a00a69fae064.PNG)
