### ISSUE TITLE
items - 13, 14, 15, and 16

### ISSUE THREAD

**Issue by stevepablow** [TurkerKucuk/Pablow_Webapp#86]
item 13 - like text to: http://www.csatravelprotection.com/certpolicy.do?product=G-330CSA

item 14 - delete entire section

item 15 - change the word policy to "plan" both times.

item 16 - Change text to "CSA's Customer Service Department at (866) 999-4018"
![csa-complaince-change-13-14-15-16](https://cloud.githubusercontent.com/assets/9828657/10408832/fb92ad40-6ece-11e5-918a-fac5ca7f8c02.jpg)

**Comment by TurkerKucuk** [comment]
done.
