### ISSUE TITLE
items 19, 20, and 21

### ISSUE THREAD

**Issue by stevepablow** [TurkerKucuk/Pablow_Webapp#88]
item 19 - replace with: plan

item 20: replace entire red line with: http://www.csaclaims.com/

item 21: add full stop .
![csa-complaince-change-19-20-21](https://cloud.githubusercontent.com/assets/9828657/10408901/80a69f90-6ed0-11e5-8a8f-5294ada09de9.jpg)

**Comment by TurkerKucuk** [comment]
done.
