### ISSUE TITLE
items 23, 24, 25, 26

### ISSUE THREAD

**Issue by stevepablow** [TurkerKucuk/Pablow_Webapp#90]
item 23 - replace with: Benefit Limit

Item 24 - replace with: Benefit Limit

Item 25 - add: Coverage

Item 26 - add a dash "-" between: dismemberment - Travel
![csa-complaince-change-23-24-25-26](https://cloud.githubusercontent.com/assets/9828657/10408947/d6a247e4-6ed2-11e5-9bd8-0efa2e61230f.jpg)

**Comment by TurkerKucuk** [comment]
done.
