### ISSUE TITLE
items 27 & 28

### ISSUE THREAD

**Issue by stevepablow** [TurkerKucuk/Pablow_Webapp#91]
Item 27 - replace this whole text with the text from FAQ for "pre-existing medical condition" which is also the text from item 13

item 28 - add this text under this paragraph: "Note: Teladoc services may not be available in all states, and international services may be limited."
![csa-complaince-change-27-28](https://cloud.githubusercontent.com/assets/9828657/10408997/35eae3b8-6ed4-11e5-8b7f-c50789009951.jpg)

**Comment by TurkerKucuk** [comment]
done.
