### ISSUE TITLE
item 29 

### ISSUE THREAD

**Issue by stevepablow** [TurkerKucuk/Pablow_Webapp#92]
item 29 - replace entire text with: 

A service that provides assistance when your identity has been compromised while traveling on your vacation. This service is automatically included for a full 180 days starting on your scheduled departure date. ID Theft Resolution does not include, and shall not assist you for thefts involving non-U.S. bank accounts.
![csa-complaince-change-29](https://cloud.githubusercontent.com/assets/9828657/10409008/9c392300-6ed4-11e5-8520-5cfd537d2b41.jpg)

**Comment by TurkerKucuk** [comment]
done.
