### ISSUE TITLE
Add updated CSA logo & compliance approval code B075_15_10

### ISSUE THREAD

**Issue by stevepablow** [TurkerKucuk/Pablow_Webapp#94]
Hey Turker - happy friday!

we got final approval from CSA for the site! woohoo!

Can you please do three things (two easy and one a favour ;-)

1. please update the existing logo. Attached a small version with rounded corners.

2. can you add this approval code: Approval Code: B075_15_10 (please add this to the bottom right of the Generali disclaimer)

3rd is change to splash page and I will add that separate

![csa-logo-v2-final-smaller-rounded-2](https://cloud.githubusercontent.com/assets/9828657/10618655/bed36b9a-7736-11e5-933d-cbb7c65469c0.jpg)

**Comment by TurkerKucuk** [comment]
Hi Steve,

I can change the logo but this is not a proper logo. There is white space around the logo and even if I try to crop it, it won't look good (because of rounded the corner and shadow). Plus, image pixel depth is not very high so it would look awkward on the page. Is this the logo CSA gave you?

**Comment by TurkerKucuk** [comment]
Can you mark on this snapshot where the approval code should be?
![item31](https://cloud.githubusercontent.com/assets/10276667/10627161/d1ce67dc-777b-11e5-938a-a5630e3ee23d.PNG)

**Comment by stevepablow** [comment]
I've attached the logo CSA sent me - maybe see if you can make it look
better. I tried to upload to github but didnt accept eps files.

yeah I did a bit of a hack job on that logo ;-)

On Tue, Oct 20, 2015 at 10:42 PM, Turker <notifications@github.com> wrote:

> Hi Steve,
>
> I can change the logo but this is not a proper logo. There is white space
> around the logo and even if I try to crop it, it won't look good (because
> of rounded the corner and shadow). Plus, image pixel depth is not very high
> so it would look awkward on the page. Is this the logo CSA gave you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TurkerKucuk/Pablow_Webapp/issues/94#issuecomment-149772152>
> .
>



-- 

________________

Steve Sherlock
CEO

 Pablow Inc
*Targeted Travel Insurance*

321 E. Walnut, Suite 130
Des Moines, IA 50309
www.Pablow.com <http://www.pablow.com/>
steve@pablow.com
+1 650 471 4495
Skype: SteveSherlock2

**Comment by stevepablow** [comment]
I think put it here - move pablow text over to left a bit and insert it
(because on their own site they put it next to their company number too)

[image: Inline image 1]

On Tue, Oct 20, 2015 at 10:42 PM, Turker <notifications@github.com> wrote:

> Can you mark on this snapshot where the approval code should be?
> [image: item31]
> <https://cloud.githubusercontent.com/assets/10276667/10627161/d1ce67dc-777b-11e5-938a-a5630e3ee23d.PNG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TurkerKucuk/Pablow_Webapp/issues/94#issuecomment-149772217>
> .
>



-- 

________________

Steve Sherlock
CEO

 Pablow Inc
*Targeted Travel Insurance*

321 E. Walnut, Suite 130
Des Moines, IA 50309
www.Pablow.com <http://www.pablow.com/>
steve@pablow.com
+1 650 471 4495
Skype: SteveSherlock2

**Comment by stevepablow** [comment]
Turker - CSA have given me an exact screen shot for where the code should go. It should be aligned on the right side, on the line after the disclaimer. Please see below. tx

![approval-code-placement-2](https://cloud.githubusercontent.com/assets/9828657/10649485/123cf52a-780a-11e5-9fb6-21a6d28a7b6d.jpg)

**Comment by TurkerKucuk** [comment]
ok, how about like this
![item33](https://cloud.githubusercontent.com/assets/10276667/10651821/50ad474e-7817-11e5-9c2c-22e894301a6c.PNG)

**Comment by TurkerKucuk** [comment]
Steve,

can you let me know if this layout is acceptable?

**Comment by stevepablow** [comment]
yep thats good. tx - sorry I missed that one.

On Thu, Oct 29, 2015 at 4:53 PM, Turker <notifications@github.com> wrote:

> Steve,
>
> can you let me know if this layout is acceptable?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TurkerKucuk/Pablow_Webapp/issues/94#issuecomment-152339059>
> .
>



-- 

________________

Steve Sherlock
CEO

 Pablow Inc
*Targeted Travel Insurance*

321 E. Walnut, Suite 130
Des Moines, IA 50309
www.Pablow.com <http://www.pablow.com/>
steve@pablow.com
+1 650 471 4495
Skype: SteveSherlock2

**Comment by TurkerKucuk** [comment]
changes have been deployed.
