### ISSUE TITLE
Update splash page - resize image, font and text background

### ISSUE THREAD

**Issue by stevepablow** [TurkerKucuk/Pablow_Webapp#95]
Turker - can you please update splash image as per attached.

I think its too big in height and the text background isn't dark enough (was also feedback from CSA)

Let me know what you think?

Once this is done we are almost ready to go. The only other thing is to remove a few states from the menu on pay page (I will confirm which to remove soon)

Attached are:

1. mockup of the page
![white-label-splash-smaller-20-oct15-v1](https://cloud.githubusercontent.com/assets/9828657/10618836/c269697a-7737-11e5-9065-bb59c4224c19.jpg)

2. splash image only - re-sized 
![white-label-splash-only-sml-v1](https://cloud.githubusercontent.com/assets/9828657/10618855/eb12108e-7737-11e5-9923-7508dbccea5e.jpg)

3. Image of text with purple background or you can create this on the page (whatever works best)
![text-on-splash-image-1](https://cloud.githubusercontent.com/assets/9828657/10618914/3fd840a2-7738-11e5-9c2c-3bf991feda76.jpg)

4. I change the font too - above the search box (you can find font on http://www.rentalcars.com/)
![image](https://cloud.githubusercontent.com/assets/9828657/10618925/586c96b8-7738-11e5-9fc8-fc5d9c4ce4e9.png)

**Comment by TurkerKucuk** [comment]
How about like this?

![item32](https://cloud.githubusercontent.com/assets/10276667/10627202/27d08642-777c-11e5-8c80-45b31fbf1301.PNG)

**Comment by TurkerKucuk** [comment]
Do you want me to use a different font altogether or the current font with a shadow as shown above?

**Comment by stevepablow** [comment]
yeah that looks better with darker purple and right adjusted text

also I think the font you have with shadow stands out and better styling
than the think font.

as you can see I am no designer :-)

--

eventually we'll get design help once we get past MVP stage, but you do a
good enough design job for this phase.

tx



On Tue, Oct 20, 2015 at 10:50 PM, Turker <notifications@github.com> wrote:

> How about like this?
>
> [image: item32]
> <https://cloud.githubusercontent.com/assets/10276667/10627202/27d08642-777c-11e5-8c80-45b31fbf1301.PNG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TurkerKucuk/Pablow_Webapp/issues/95#issuecomment-149772812>
> .
>



-- 

________________

Steve Sherlock
CEO

 Pablow Inc
*Targeted Travel Insurance*

321 E. Walnut, Suite 130
Des Moines, IA 50309
www.Pablow.com <http://www.pablow.com/>
steve@pablow.com
+1 650 471 4495
Skype: SteveSherlock2

**Comment by TurkerKucuk** [comment]
this is done also while back. just never closed the ticket. closing now.
