### ISSUE TITLE
Add Lodgix logo to white label

### ISSUE THREAD

**Issue by stevepablow** [TurkerKucuk/Pablow_Webapp#96]
Turker

Lodgix have asked to add their logo to the splash page and in header on further pages. So basically just replacing the Pablow icon.

Attached

1. Logo placement on home page

![lodgix-logo-placement](https://cloud.githubusercontent.com/assets/9828657/10627359/13462144-777e-11e5-924e-dc71a8fd6eac.jpg)

2. Logo placement on further pages

![lodgix-logo-placement-2nd](https://cloud.githubusercontent.com/assets/9828657/10627366/27785e66-777e-11e5-9fbc-c268c77b7039.jpg)

3 The white logo jpg

![lodgix-logo-white-trans](https://cloud.githubusercontent.com/assets/9828657/10627375/3aa548aa-777e-11e5-8a14-66c2f322b4b7.jpg)

In case you need a better Lodgix logo here are their options. (i'll email as it doesn't load here)

Thanks,
Steve

Thanks
Steve

**Comment by stevepablow** [comment]
forgot something - on the home page can you link the lodgix logo to http://www.lodgix.com/

And on all the other pages - as per normal just link to home page. tx

**Comment by TurkerKucuk** [comment]
Hi Steve,

Lodgix provided us a black logo. Here is how it looks on home page and other pages. 

![item34](https://cloud.githubusercontent.com/assets/10276667/10832647/99837e90-7e5a-11e5-9130-6628e6d850d1.PNG)
![item35](https://cloud.githubusercontent.com/assets/10276667/10832648/9983be82-7e5a-11e5-8748-fdf88bf96b07.PNG)

We had requested a white version of the logo. Let me know what to do as our page is really designed to work with a white version of the logo.

**Comment by TurkerKucuk** [comment]
I can make the navigation bar to be gray and then logo will be fine.
![item37](https://cloud.githubusercontent.com/assets/10276667/10833218/50f920f4-7e5e-11e5-82ea-1b1a6f7a7ff2.PNG)

**Comment by stevepablow** [comment]
yeah good idea - the grey actually looks pretty good - brightens up page
and matches the gray panel

On Thu, Oct 29, 2015 at 4:58 PM, Turker <notifications@github.com> wrote:

> I can make the navigation bar to be gray and then logo will be fine.
> [image: item37]
> <https://cloud.githubusercontent.com/assets/10276667/10833218/50f920f4-7e5e-11e5-82ea-1b1a6f7a7ff2.PNG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TurkerKucuk/Pablow_Webapp/issues/96#issuecomment-152340128>
> .
>



-- 

________________

Steve Sherlock
CEO

 Pablow Inc
*Targeted Travel Insurance*

321 E. Walnut, Suite 130
Des Moines, IA 50309
www.Pablow.com <http://www.pablow.com/>
steve@pablow.com
+1 650 471 4495
Skype: SteveSherlock2

**Comment by TurkerKucuk** [comment]
website has been deployed. ticket closed.
