### ISSUE TITLE
add link to payment page

### ISSUE THREAD

**Issue by stevepablow** [TurkerKucuk/Pablow_Webapp#97]
can you add text as per the mockup. Because this page doesn't have any coverage details. Later we could consider adding the full coverage back into the left hand column - but for now I think this link will do the job.

Guest Protect Plan 
Coverage Details
(opens in new window)

![payment-page-add-product-link](https://cloud.githubusercontent.com/assets/9828657/10705699/7d2779b8-79a5-11e5-8d55-1058494e83a0.jpg)

**Comment by TurkerKucuk** [comment]
done...
![item36](https://cloud.githubusercontent.com/assets/10276667/10832938/742ac76e-7e5c-11e5-90ec-c163164f9c9f.PNG)
